/**
 * Reusable sync engine — extracts the Payload → markdown conversion
 * logic from scripts/sync-to-website.ts so it can be called from both:
 *   1. The CLI script (writes to local filesystem, used for manual sync)
 *   2. The /api/regenerate endpoint (writes to GitHub via Contents API,
 *      used by afterChange hooks on content collections)
 *
 * Returns a Map<repoRelativePath, fileContent> that the caller writes
 * however it wants. Pure function — no I/O side effects.
 */

import type { Payload } from 'payload'
import { convertLexicalToMarkdown } from '@payloadcms/richtext-lexical'

/** Wildcards that can't live in Payload's exact-match Redirects schema. */
const REDIRECT_WILDCARDS = `# ─── Wildcards (static) ─────────────────────────────────────────────
/marketing-journal/*   /blog/:splat   301
/portfolio/*           /about/        301
/case-studies/*        /about/        301
/work/*                /about/        301

# ─── Sitemap aliases ────────────────────────────────────────────────
/sitemap_index.xml     /sitemap-index.xml   301
`

const REDIRECTS_HEADER = `# AUTO-GENERATED by chirobasix-payload-backend.
# DO NOT EDIT BY HAND — edits will be wiped on next sync. Manage redirects
# at https://admin.chirobasix.com/admin/collections/redirects (or the
# active Payload admin URL).

`

// ── YAML serializer (same as scripts/sync-to-website.ts) ─────────────

function yamlValue(v: unknown, indent = 0): string {
  if (v === null || v === undefined) return ''
  if (typeof v === 'string') {
    if (/[\n:#"'`*&!|>%@`,\[\]{}]/.test(v) || /^\s|\s$/.test(v)) {
      return JSON.stringify(v)
    }
    return v
  }
  if (typeof v === 'number' || typeof v === 'boolean') return String(v)
  if (v instanceof Date) return v.toISOString()
  if (Array.isArray(v)) {
    if (v.length === 0) return '[]'
    const pad = ' '.repeat(indent)
    return '\n' + v.map((item) => {
      if (typeof item === 'object' && item !== null) {
        const entries = Object.entries(item).filter(([k, val]) => {
          if (val === undefined || val === null || val === '') return false
          if (k === 'id') {
            if (typeof val === 'number') return false
            if (typeof val === 'string' && /^[0-9a-f]{8}-[0-9a-f]{4}|^[0-9a-f]{24}$/.test(val)) return false
          }
          return true
        })
        return entries
          .map(([k, val], i) => `${pad}${i === 0 ? '- ' : '  '}${k}: ${yamlValue(val, indent + 4)}`)
          .join('\n')
      }
      return `${pad}- ${yamlValue(item)}`
    }).join('\n')
  }
  if (typeof v === 'object') {
    const pad = ' '.repeat(indent)
    return '\n' + Object.entries(v as Record<string, unknown>)
      .filter(([k]) => k !== 'id')
      .map(([k, val]) => `${pad}${k}: ${yamlValue(val, indent + 2)}`)
      .join('\n')
  }
  return ''
}

function buildFrontmatter(data: Record<string, unknown>): string {
  const lines: string[] = ['---']
  for (const [k, v] of Object.entries(data)) {
    if (v === undefined || v === null || v === '') continue
    if (Array.isArray(v) && v.length === 0) continue
    lines.push(`${k}: ${yamlValue(v, 2)}`)
  }
  lines.push('---', '')
  return lines.join('\n')
}

function imageUrl(field: unknown): string | undefined {
  if (!field) return undefined
  if (typeof field === 'string') return field
  if (typeof field === 'object' && field !== null) {
    return (field as { url?: string }).url || undefined
  }
  return undefined
}

interface SyncContext {
  payload: Payload
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  editorConfig: any
}

function bodyMarkdown(ctx: SyncContext, body: unknown): string {
  if (!body) return ''
  try {
    return convertLexicalToMarkdown({ data: body as never, editorConfig: ctx.editorConfig })
  } catch (e) {
    console.error('    body conversion FAIL:', (e as Error).message?.slice(0, 200))
    return ''
  }
}

// ─── Mappers ────────────────────────────────────────────────────────

function mapPage(ctx: SyncContext, d: Record<string, unknown>) {
  return {
    slug: d.slug as string,
    frontmatter: { title: d.title, description: d.description, ogImage: imageUrl(d.ogImage) },
    body: bodyMarkdown(ctx, d.body),
  }
}

function mapService(ctx: SyncContext, d: Record<string, unknown>) {
  return {
    slug: d.slug as string,
    frontmatter: {
      title: d.title, subtitle: d.subtitle, eyebrow: d.eyebrow,
      description: d.description, heroImage: imageUrl(d.heroImage),
      cta: d.cta, publishDate: d.publishDate, ogImage: imageUrl(d.ogImage),
    },
    body: bodyMarkdown(ctx, d.body),
  }
}

function mapBlog(ctx: SyncContext, d: Record<string, unknown>) {
  return {
    slug: d.slug as string,
    frontmatter: {
      title: d.title, description: d.description, publishDate: d.publishDate,
      updateDate: d.updateDate, author: d.author, category: d.category,
      heroImage: imageUrl(d.heroImage), heroImageAlt: d.heroImageAlt,
      excerpt: d.excerpt, readingTimeMinutes: d.readingTimeMinutes,
      tags: (d.tags as Array<{ tag: string }> | undefined)?.map((t) => t.tag),
      tocAnchors: (d.tocAnchors as Array<{ anchor: string; label: string }> | undefined)?.map((a) => ({
        id: a.anchor, label: a.label,
      })),
      ogImage: imageUrl(d.ogImage),
    },
    body: bodyMarkdown(ctx, d.body),
  }
}

function mapPodcast(ctx: SyncContext, d: Record<string, unknown>) {
  return {
    slug: d.slug as string,
    frontmatter: {
      title: d.title, description: d.description,
      episodeNumber: d.episodeNumber, seasonNumber: d.seasonNumber,
      category: d.category, publishDate: d.publishDate,
      audioEmbedHtml: d.audioEmbedHtml, audioUrl: d.audioUrl,
      durationLabel: d.durationLabel, durationMinutes: d.durationMinutes,
      videoEmbedUrl: d.videoEmbedUrl, youtubeId: d.youtubeId,
      hosts: (d.hosts as Array<{ name: string }> | undefined)?.map((h) => h.name),
      guests: (d.guests as Array<{ name: string }> | undefined)?.map((g) => g.name),
      chapters: d.chapters, linksMentioned: d.linksMentioned, transcript: d.transcript,
      tags: (d.tags as Array<{ tag: string }> | undefined)?.map((t) => t.tag),
      showNotes: d.showNotes, heroImage: imageUrl(d.heroImage), ogImage: imageUrl(d.ogImage),
    },
    body: bodyMarkdown(ctx, d.body),
  }
}

function mapResource(ctx: SyncContext, d: Record<string, unknown>) {
  return {
    slug: d.slug as string,
    frontmatter: {
      title: d.title, description: d.description, leadMagnetType: d.leadMagnetType,
      heroImage: imageUrl(d.heroImage), formFields: d.formFields,
      postSubmitRedirect: d.postSubmitRedirect, ogImage: imageUrl(d.ogImage),
    },
    body: bodyMarkdown(ctx, d.body),
  }
}

// ─── Public: generate the full file set ─────────────────────────────

interface SyncResult {
  files: Map<string, string>  // repoRelativePath → content
  counts: Record<string, number>
}

const COLLECTIONS = [
  { slug: 'pages',     dir: 'src/content/pages',     mapper: mapPage },
  { slug: 'services',  dir: 'src/content/services',  mapper: mapService },
  { slug: 'blog',      dir: 'src/content/blog',      mapper: mapBlog },
  { slug: 'podcast',   dir: 'src/content/podcast',   mapper: mapPodcast },
  { slug: 'resources', dir: 'src/content/resources', mapper: mapResource },
] as const

export async function generateSyncFiles(payload: Payload, editorConfig: unknown): Promise<SyncResult> {
  const ctx: SyncContext = { payload, editorConfig }
  const files = new Map<string, string>()
  const counts: Record<string, number> = {}

  for (const col of COLLECTIONS) {
    const { docs } = await payload.find({ collection: col.slug, limit: 500, depth: 2 })
    counts[col.slug] = docs.length
    for (const doc of docs) {
      const { slug, frontmatter, body } = col.mapper(ctx, doc as unknown as Record<string, unknown>)
      const md = buildFrontmatter(frontmatter) + body + (body.endsWith('\n') ? '' : '\n')
      files.set(`${col.dir}/${slug}.md`, md)
    }
  }

  // Redirects → public/_redirects
  const { docs: redirectDocs } = await payload.find({ collection: 'redirects', limit: 5000, depth: 0 })
  counts.redirects = redirectDocs.length
  const sorted = (redirectDocs as Array<{ fromPath: string; toPath: string; statusCode: string | number }>)
    .sort((a, b) => b.fromPath.length - a.fromPath.length)
  const redirectLines = sorted.map((r) => `${r.fromPath}   ${r.toPath}   ${r.statusCode || 301}`)
  const redirectsFile =
    REDIRECTS_HEADER +
    '# ─── Payload-managed (exact-match) ──────────────────────────────────\n' +
    redirectLines.join('\n') + '\n\n' +
    REDIRECT_WILDCARDS
  files.set('public/_redirects', redirectsFile)

  return { files, counts }
}
